### PR TITLE
Do not add import when targetElement not present

### PR DESCRIPTION
**Pull request by heidivanparys**
In the XML Do not add an import statement, nor a declaration of the XML
namespace abbrevation, when rule rule-xsd-prop-targetElement is not
enabled.

The import statement is not needed when rule-xsd-prop-targetElement is
not enabled. When it is present, and the XML schema that is referred to,
does not exist, it makes the XML validation fail.

A reason for the non-existence of the XML schema can be that the
application schema is maintained by another organation, that uses
another encoding than XML.

### CODE REVIEW

**Comment by heidivanparys** [comment]
The change in test_prop.eap is the addition of an application schema, containing a feature type with a reference to a feature type in the already exisisting application schema.

image

A test was added to XMLSchemaTest, and all tests in this test class pass.

**Comment by heidivanparys** [comment]
Without the code change, the first lines in test2_prop.xsd would look as follows:
```
<schema
xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:test="http://shapechange.net/test"
xmlns:test2="http://shapechange.net/test2"
elementFormDefault="qualified"
targetNamespace="http://shapechange.net/test2"
version="1.0">
  <import namespace="http://shapechange.net/test"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
<!--XML Schema document created by ShapeChange - http://shapechange.net/-->
```

With the code change, they look as follows:

```
<schema
xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:test2="http://shapechange.net/test2"
elementFormDefault="qualified"
targetNamespace="http://shapechange.net/test2"
version="1.0">
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
<!--XML Schema document created by ShapeChange - http://shapechange.net/-->
```

**Comment by jechterhoff** [comment]
As far as I know, an <import> element with just a namespace attribute in it is fine. XSD validation may issue a warning but not an error. Such an import would simply allow reference to foreign components in that namespace without giving any hints as to where to find them.

https://www.w3.org/TR/xmlschema-1/#element-import says:
> It is not an error for the application schema reference strategy to fail.

Does your XML Schema processor actually report an error if it encounters an <import> without a schemaLocation attribute?

**Comment by cportele** [comment]
Independent of the question whether a schema parser reports an error, it does make sense to not add the import, if the namespace is not used anywhere in the schema document.

**Comment by heidivanparys** [comment]
If no schemaLocation is set, the file validates fine in Eclipse, XMLSpy issues a warning and then says the file is valid.
image

I have asked the person responsible for the WFS set-up to check what Go Publisher does in this case, if it can use the GML application schema or not.

However, the governance issue still remains: my organization has to decide on a namespace for a model that we do not own, and the data are likely not be exposed via GML/WFS.

**Pull request merged**
