### PR TITLE
Flattener update

### PR DESCRIPTION
**Pull request by heidivanparys**
1. Refactor the creation of a Type based on a type name and a generic model
2. Update multiplicity calculation for fixed uom property (flattener) (#267 )
3. Add rules for flattening properties of type MediaType and DirectPosition

Examples:

format (MediaType):

- format (CharacterString), e.g. "PDF"
- format_type (CharacterString), e.g. "application/pdf"

height (DirectPosition):

- height (Real), e.g. 7
- height_crs (CharacterString), e.g. "http://www.opengis.net/def/crs/EPSG/0/5799"

### CODE REVIEW

**Comment by heidivanparys** [comment]
@jechterhoff Could you please review these changes?

**Comment by jechterhoff** [comment]
@heidivanparys Thanks for the pull request and the improvements to code and functionality. 

Clemens can give you access to our documentation so that you can make the modifications and additions (of the new transformation rules) yourself. Are you ok with that?

**Comment by heidivanparys** [comment]
@jechterhoff  Yes, I'm ok with that.

**Comment by jechterhoff** [comment]
Great, thanks.

**Pull request merged**
